import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from "react";
import Provider from "@/src/backend/trpc/Provider";
import AuthProvider from "@/src/frontend/context/AuthProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next myapp',
  description: 'Generated by create next myapp',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <AuthProvider>
      <Provider>
        {children}
      </Provider>
    </AuthProvider>
    </body>
    </html>
  )
}
